export const TRANSACTIONS_VOLUMES = [
  "£1,000 - £100,000",
  "£100,001 - £500,000",
  "£500,001 - £750,000",
  "£750,001 - £1,000,000",
];

export const CURRENCIES = [
  { code: "AED", name: "United Arab Emirates Dirham" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "British Pound" },
  { code: "NGN", name: "Nigerian Naira" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "UAH", name: "Ukrainian Hryvnia" },
  { code: "USD", name: "United States Dollar" },
  { code: "XAF", name: "Central African Franc" },
  { code: "XOF", name: "West African CFA Franc" },
];

export const TYPES_OF_BUSINESS = [
  "Private Unlimited",
  "Ltd",
  "Plc",
  "Old Public Company",
  "Private Limited Guarant Nsc Limited Exemption",
  "Private Limited Guarant Nsc",
  "Converted Or Closed",
  "Private Unlimited Nsc",
  "Private Limited Shares Section 30 Exemption",
  "Assurance Company",
  "Oversea Company",
  "Eeig",
  "Icvc Securities",
  "Icvc Warrant",
  "Industrial And Provident Society",
  "Royal Charter",
  "Investment Company With Variable Capital",
  "Unregistered Company",
  "Llp",
  "European Public Limited Liability Company Se",
  "Registered Overseas Entity",
  "Uk Establishment",
  "Registered Society",
  "Protected Cell Company",
  "Scottish Partnership",
  "Charitable Incorporated Organisation",
  "Scottish Charitable Incorporated Organisation",
  "United Kingdom Economic Interest Groupings",
  "United Kingdom Societas",
  "Other",
];

export const BUSINESS_INDUSTRIES = [
  "High Risk - Adult content and services",
  "High Risk - Agriculture / Farming",
  "High Risk - Art Dealers",
  "High Risk - Boat Dealers",
  "High Risk - Business active in government procurement",
  "High Risk - Cash-intensive business including beauty parlours, newsagents, restaurants, bars, nightclubs, public houses, takeaways, and car washes",
  "High Risk - Chemical Manufacturing",
  "High Risk - Clothing Manufacturing",
  "High Risk - Construction and (large) infrastructure",
  "High Risk - Crowdfunding",
  "High Risk - Cryptocurrency / Regulated Forex Exchange",
  "High Risk - Cyberlocker (an internet service that allows users to store and share files online)",
  "High Risk - Development and other types of assistance",
  "High Risk - Estate Agency Business (EAB)",
  "High Risk - Free port operator",
  "High Risk - Gaming / Casinos / Amusements",
  "High Risk - High value dealers including luxury goods, precious metals, and precious stones",
  "High Risk - Language Schools",
  "High Risk - Letting Agency Business (LAB)",
  "High Risk - Marinas",
  "High Risk - Mining and extraction",
  "High Risk - Negative option billing",
  "High Risk - Non EEA Charities or EEA Non Registered or Non Regulated Charities",
  "High Risk - Oil and Gas Pipeline and Related Structures Construction",
  "High Risk - Paper Manufacturing",
  "High Risk - Petroleum",
  "High Risk - Pharmaceutical",
  "High Risk - Plastics Rubber Metal Manufacturing",
  "High Risk - Precious Metal Production",
  "High Risk - Privatisation",
  "High Risk - Professional football",
  "High Risk - Property",
  "High Risk - Provision of public goods utilities",
  "High Risk - Securities",
  "High Risk - Sugar",
  "High Risk - Tobacco",
  "High Risk - Travel / Travel Agencies / Tour Operators",
  "High Risk - Trust and Company Service Provider (TCSP)",
  "High Risk - Wealth management & private banking",
  "High Risk - Wholesale banking",
  "Medium Risk - Automtive",
  "Medium Risk - Beverage Manufacture",
  "Medium Risk - Book Stores",
  "Medium Risk - Catering",
  "Medium Risk - Colleges Universities and Professional Schools",
  "Medium Risk - Consumer Banking / Prepaid Cards / Debit Cards / Credit Cards",
  "Medium Risk - Consumer Shops",
  "Medium Risk - Corporate Payroll",
  "Medium Risk - Dentist Related",
  "Medium Risk - E-Money / E-Wallets",
  "Medium Risk - EEA Registered or Regulated Charities",
  "Medium Risk - Electrical Contractors",
  "Medium Risk - Health Care / Hospitals / Medical",
  "Medium Risk - Insurance Related Activities",
  "Medium Risk - Money Remittance",
  "Medium Risk - News Publication",
  "Medium Risk - Optical - Eye Assessments / Eye Wear / Eye Treatment",
  "Medium Risk - Paint Manufacturing",
  "Medium Risk - Plumbing Heating and Air-Conditioning Contractors",
  "Medium Risk - Postal Service",
  "Medium Risk - Regulated Professional Services (Legal Accountancy etc.)",
  "Medium Risk - Renewable Energy",
  "Medium Risk - State Owned Entity / Civil Service",
  "Medium Risk - Telecoms / Telecommunication / Internet",
  "Medium Risk - Transportation",
  "Low Risk - Glass and Glazing Contractors",
  "Low Risk - Government Sponsored Private Entity (not owned)",
  "Low Risk - Museums",
  "Low Risk - Regulated Businesses",
  "Other Services",
];

export const PURPOSES_OF_ACCOUNT = [
  "A business account simplifies tax preparation",
  "A business account necessary to form a partnership or incorporate",
  "A business account",
  "A business account for operations and payroll",
  "A business account for fund exchange and international payment",
  "A business account to receive funds as a Freelancer / Sole Trader",
  "A business account to receive payment from buyers",
  "A business account to pay suppliers",
];
